"""Permutation groups, without SageMath.

The thesis names every node's automorphism group -- ``C2``, ``D4``, ``S4``,
``C2 x S4``, ``PSL(3,2)``, ``(((C2 x C2 x C2 x C2) : C2) : C2) : C2``
(Figures 5.1-5.4). This is the pure-Python fallback for machines without
SageMath; where Sage is present :mod:`fka.backends.sage_backend` defers to GAP's
``StructureDescription``, which is authoritative.

Naming is by *invariant fingerprint*, not a proof of isomorphism. A group is
matched against candidates of the same order -- cyclic, dihedral, symmetric,
alternating, quaternion, and their direct and wreath products -- on order, the
multiset of element orders, abelian-ness, centre order, derived-subgroup order,
and the multiset of conjugacy class sizes. Two non-isomorphic groups agreeing on
all six would be misnamed; that does not happen for anything in the thesis'
figures, but the limitation is real. :func:`identify` reports how it matched and
returns an ``order N`` placeholder rather than a guess when nothing fits.

Candidates are derived from the order arithmetically -- ``D_m`` is a candidate
for ``2m``, ``S_k`` for ``k!`` -- so nothing is enumerated that the order
already rules out. The two infinite families are recognised *without* being
constructed: a cyclic group is an abelian group with an element of full order, a
dihedral one has the rotation and the reflection count. That matters, because
building ``D720`` to compare against a group of order 1440 costs more than the
answer is worth.

Permutations are tuples of images on ``0 .. n-1``: ``p[i]`` is the image of ``i``.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from functools import lru_cache
from math import factorial, isqrt, lcm, prod
from typing import Callable, Iterator, Optional, Sequence

__all__ = [
    "Perm",
    "identity",
    "compose",
    "inverse",
    "conjugate",
    "commutator",
    "perm_order",
    "cycle_notation",
    "closure",
    "PermutationGroup",
    "identify",
]

Perm = tuple[int, ...]

#: Upper bound on how many group elements will be enumerated. Every group in
#: the thesis is far below this; the cap turns a runaway case into a clear
#: error instead of an apparent hang.
MAX_GROUP_ORDER = 200_000

#: Groups above this order are not matched against candidates: enumerating
#: their elements and conjugacy classes stops being cheap, and nothing in the
#: thesis needs it. Larger groups fall through to :data:`_SPECIAL` or come back
#: unidentified, which is a prompt to run the SageMath backend.
MAX_CATALOGUE_ORDER = 2_000

#: Atoms above this order are not *constructed* as product factors. Cost is
#: degree times order, so a large ``C_n`` or ``D_m`` is expensive to build and
#: almost never the answer -- and when it is, :func:`_named_cyclic` and
#: :func:`_named_dihedral` name it without building anything.
MAX_ATOM_ORDER = 256


def identity(n: int) -> Perm:
    return tuple(range(n))


def compose(p: Perm, q: Perm) -> Perm:
    """``(p . q)(i) = p(q(i))``."""
    return tuple(p[q[i]] for i in range(len(q)))


def inverse(p: Perm) -> Perm:
    out = [0] * len(p)
    for i, x in enumerate(p):
        out[x] = i
    return tuple(out)


def conjugate(g: Perm, x: Perm) -> Perm:
    """``g x g^-1``."""
    return compose(compose(g, x), inverse(g))


def commutator(a: Perm, b: Perm) -> Perm:
    """``[a, b] = a b a^-1 b^-1``."""
    return compose(compose(a, b), compose(inverse(a), inverse(b)))


def perm_order(p: Perm) -> int:
    """Multiplicative order of ``p``."""
    n = len(p)
    seen = [False] * n
    order = 1
    for i in range(n):
        if seen[i]:
            continue
        length = 0
        j = i
        while not seen[j]:
            seen[j] = True
            j = p[j]
            length += 1
        order = lcm(order, length)
    return order


def cycle_notation(p: Perm, *, one_indexed: bool = True) -> str:
    """Render ``p`` in disjoint-cycle notation, e.g. ``(1,4)(5,6)``.

    Fixed points are omitted; the identity renders as ``()``.
    """
    shift = 1 if one_indexed else 0
    n = len(p)
    seen = [False] * n
    parts: list[str] = []
    for i in range(n):
        if seen[i] or p[i] == i:
            seen[i] = True
            continue
        cycle = []
        j = i
        while not seen[j]:
            seen[j] = True
            cycle.append(j + shift)
            j = p[j]
        if len(cycle) > 1:
            parts.append("(" + ",".join(map(str, cycle)) + ")")
    return "".join(parts) if parts else "()"


def closure(
    generators: Sequence[Perm], n: int, *, cap: int = MAX_GROUP_ORDER
) -> list[Perm]:
    """All elements of the group generated by ``generators`` (breadth-first)."""
    e = identity(n)
    seen = {e}
    frontier = [e]
    gens = [g for g in generators if g != e]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(g, x)
                if y not in seen:
                    seen.add(y)
                    if len(seen) > cap:
                        raise ValueError(
                            f"group exceeded {cap} elements; refusing to enumerate further"
                        )
                    nxt.append(y)
        frontier = nxt
    return sorted(seen)


@dataclass(slots=True)
class PermutationGroup:
    """A finite permutation group given by its full element list.

    Built from generators via :meth:`from_generators`. Holding every element is
    wasteful in general but is the simplest thing that supports the invariants
    below exactly, and the groups here are small by construction.

    The invariants take ``generators or elements``: a subgroup-defining property
    that holds on a generating set holds on the whole group, so the generators
    are enough wherever one is available, and the element list is the honest
    fallback when :class:`PermutationGroup` was built without them.
    """

    degree: int
    elements: list[Perm]
    generators: list[Perm] = field(default_factory=list)
    #: Memoised. The full fingerprint needs conjugacy classes, and a lookup
    #: compares many candidates against one query.
    _cheap: Optional[tuple] = None
    _fingerprint: Optional[tuple] = None

    @classmethod
    def from_generators(
        cls, generators: Sequence[Perm], n: int, *, cap: int = MAX_GROUP_ORDER
    ) -> "PermutationGroup":
        elements = closure(generators, n, cap=cap)
        return cls(degree=n, elements=elements, generators=list(generators))

    @property
    def order(self) -> int:
        return len(self.elements)

    def is_trivial(self) -> bool:
        return self.order == 1

    def _gens(self) -> list[Perm]:
        return self.generators or self.elements

    def element_order_profile(self) -> tuple[tuple[int, int], ...]:
        """Sorted ``(element order, count)`` pairs."""
        counts: dict[int, int] = {}
        for p in self.elements:
            o = perm_order(p)
            counts[o] = counts.get(o, 0) + 1
        return tuple(sorted(counts.items()))

    def is_abelian(self) -> bool:
        gens = self._gens()
        return all(compose(a, b) == compose(b, a) for a in gens for b in gens)

    def centre(self) -> list[Perm]:
        """``Z(G)``. Commuting with the generators is commuting with the group."""
        gens = self._gens()
        return [
            z for z in self.elements
            if all(compose(z, g) == compose(g, z) for g in gens)
        ]

    def derived_subgroup(self) -> list[Perm]:
        """``[G, G]``: the normal closure of the generators' commutators.

        Not merely the subgroup they generate -- that can be too small -- so the
        conjugates are folded back in until the set is stable.
        """
        gens = self._gens()
        K = set(closure([commutator(a, b) for a in gens for b in gens], self.degree))
        while True:
            extra = {conjugate(g, k) for g in gens for k in K} - K
            if not extra:
                return sorted(K)
            K = set(closure(sorted(K | extra), self.degree))

    def conjugacy_class_sizes(self) -> tuple[int, ...]:
        """Sorted class sizes. A class is an orbit under conjugation by generators."""
        remaining = set(self.elements)
        gens = self._gens()
        sizes: list[int] = []
        while remaining:
            x = next(iter(remaining))
            cls = {x}
            frontier = [x]
            while frontier:
                y = frontier.pop()
                for g in gens:
                    z = conjugate(g, y)
                    if z not in cls:
                        cls.add(z)
                        frontier.append(z)
            sizes.append(len(cls))
            remaining -= cls
        return tuple(sorted(sizes))

    def orbits(self) -> list[tuple[int, ...]]:
        """Orbits of the group on ``0 .. degree-1``, ascending."""
        unseen = set(range(self.degree))
        out: list[tuple[int, ...]] = []
        while unseen:
            v = min(unseen)
            orb = sorted({p[v] for p in self.elements})
            out.append(tuple(orb))
            unseen -= set(orb)
        return out

    def minimal_generators(self) -> list[Perm]:
        """A small (greedy, not provably minimum) generating set.

        Elements are tried in descending order so high-order elements are
        picked first, which tends to give the short presentations the thesis
        quotes.
        """
        if self.order == 1:
            return []
        chosen: list[Perm] = []
        current = {identity(self.degree)}
        for p in sorted(self.elements, key=lambda p: -perm_order(p)):
            if p in current:
                continue
            chosen.append(p)
            current = set(closure(chosen, self.degree))
            if len(current) == self.order:
                break
        return chosen

    def cheap_signature(self) -> tuple:
        """Order, element-order profile and abelian-ness.

        Rejects a candidate before paying for the full fingerprint.
        """
        if self._cheap is None:
            self._cheap = (self.order, self.element_order_profile(), self.is_abelian())
        return self._cheap

    def fingerprint(self) -> tuple:
        """The invariants a name is matched on. See the module docstring."""
        if self._fingerprint is None:
            self._fingerprint = self.cheap_signature() + (
                len(self.centre()),
                len(self.derived_subgroup()),
                self.conjugacy_class_sizes(),
            )
        return self._fingerprint


# ----------------------------------------------------------------------
# named groups, constructed on demand
# ----------------------------------------------------------------------
def _cyclic(n: int) -> PermutationGroup:
    return PermutationGroup.from_generators([tuple((i + 1) % n for i in range(n))], n)


def _dihedral(m: int) -> PermutationGroup:
    """Symmetries of the ``m``-gon, order ``2m``.

    The thesis and SageMath's ``DihedralGroup`` both index by the polygon, so
    ``D4`` has order 8.
    """
    rot = tuple((i + 1) % m for i in range(m))
    ref = tuple((-i) % m for i in range(m))
    return PermutationGroup.from_generators([rot, ref], m)


def _symmetric(k: int) -> PermutationGroup:
    swap = list(range(k))
    swap[0], swap[1] = swap[1], swap[0]
    return PermutationGroup.from_generators(
        [tuple(range(1, k)) + (0,), tuple(swap)], k
    )


def _alternating(k: int) -> PermutationGroup:
    gens = []
    for i in range(k - 2):
        p = list(range(k))
        p[i], p[i + 1], p[i + 2] = p[i + 1], p[i + 2], p[i]
        gens.append(tuple(p))
    return PermutationGroup.from_generators(gens, k)


#: Unit quaternion multiplication on ``1, i, j, k``: ``(index, negated)``.
#: Everything else follows from ``i^2 = j^2 = k^2 = ijk = -1``.
_IJK = {(1, 2): (3, False), (2, 3): (1, False), (3, 1): (2, False)}


def _quaternion8() -> PermutationGroup:
    """Q8 as its own regular representation on the eight units ``+-1, +-i, +-j, +-k``."""

    def mul(a: tuple[int, bool], b: tuple[int, bool]) -> tuple[int, bool]:
        (ua, na), (ub, nb) = a, b
        neg = na ^ nb
        if ua == 0:
            return ub, neg
        if ub == 0:
            return ua, neg
        if ua == ub:
            return 0, not neg  # i^2 = j^2 = k^2 = -1
        if (ua, ub) in _IJK:
            u, flip = _IJK[(ua, ub)]
        else:
            u, flip = _IJK[(ub, ua)][0], True  # anti-commutative
        return u, neg ^ flip

    units = [(u, n) for u in range(4) for n in (False, True)]
    index = {e: i for i, e in enumerate(units)}
    gens = [
        tuple(index[mul(g, x)] for x in units)
        for g in ((1, False), (2, False))  # left multiplication by i and by j
    ]
    return PermutationGroup.from_generators(gens, 8)


#: ``(name, order, builder)``. Built on demand: the fingerprint needs conjugacy
#: classes, so constructing a candidate that the order already rules out is pure
#: waste.
_Atom = tuple[str, int, Callable[[], PermutationGroup]]


def _atoms_dividing(order: int) -> Iterator[_Atom]:
    """Every named atomic group whose order divides ``order``.

    Type-major -- cyclic, dihedral, symmetric, alternating, quaternion -- so a
    group is named ``S4`` rather than as some product isomorphic to it.
    """
    for d in range(2, min(order, MAX_ATOM_ORDER) + 1):
        if order % d == 0:
            yield f"C{d}", d, lambda d=d: _cyclic(d)
    for m in range(3, min(order // 2, MAX_ATOM_ORDER // 2) + 1):
        if order % (2 * m) == 0:
            yield f"D{m}", 2 * m, lambda m=m: _dihedral(m)
    for k in itertools.count(3):
        f = factorial(k)
        if f > order:
            break
        if order % f == 0:
            yield f"S{k}", f, lambda k=k: _symmetric(k)
    for k in itertools.count(4):
        h = factorial(k) // 2
        if h > order:
            break
        if order % h == 0:
            yield f"A{k}", h, lambda k=k: _alternating(k)
    if order % 8 == 0:
        yield "Q8", 8, _quaternion8


def _product(a: PermutationGroup, b: PermutationGroup) -> PermutationGroup:
    """Direct product, acting on the disjoint union of the two point sets."""
    na, nb = a.degree, b.degree
    gens = [tuple(g) + tuple(na + i for i in range(nb)) for g in a._gens()]
    gens += [tuple(range(na)) + tuple(na + g[i] for i in range(nb)) for g in b._gens()]
    return PermutationGroup.from_generators(gens, na + nb)


def _wreath(a: PermutationGroup, b: PermutationGroup) -> PermutationGroup:
    """``A wr B``, acting imprimitively, of order ``|A|^m * |B|`` for ``m = deg B``.

    ``B`` permutes ``m`` blocks, each a copy of ``A``'s domain, and ``A`` acts
    inside one block. These are needed, not decoration: the thesis names the
    root of the f2/g2 tree ``D4 wr S2``, and Cameron's proposition (Section 4.4)
    says cograph automorphism groups are built from direct and wreath products
    with symmetric groups. Direct products alone could never name them.
    """
    p, m = a.degree, b.degree
    n = p * m
    gens: list[Perm] = []
    for g in a._gens():
        gens.append(tuple(g) + tuple(range(p, n)))
    for h in b._gens():
        img = [0] * n
        for blk in range(m):
            for i in range(p):
                img[blk * p + i] = h[blk] * p + i
        gens.append(tuple(img))
    return PermutationGroup.from_generators(gens, n)


def _exact_root(value: int, m: int) -> Optional[int]:
    """The integer ``r`` with ``r**m == value``, or ``None``."""
    r = isqrt(value) if m == 2 else round(value ** (1.0 / m))
    for cand in (r - 1, r, r + 1):
        if cand > 0 and cand**m == value:
            return cand
    return None


#: Top groups for wreath products, small enough that ``|A|^deg B`` stays modest.
_WREATH_TOPS: tuple[tuple[str, Callable[[], PermutationGroup]], ...] = (
    ("C2", lambda: _cyclic(2)),
    ("C3", lambda: _cyclic(3)),
    ("C4", lambda: _cyclic(4)),
    ("S3", lambda: _symmetric(3)),
    ("S4", lambda: _symmetric(4)),
)


@lru_cache(maxsize=256)
def _candidates(order: int) -> tuple[tuple[str, PermutationGroup], ...]:
    """Named groups of exactly ``order``, cheapest spelling first.

    Atoms, then direct products of two and of three atoms, then wreath products.
    Earlier entries win ties.
    """
    atoms = list(_atoms_dividing(order))
    built: dict[str, PermutationGroup] = {}

    def get(spec: _Atom) -> PermutationGroup:
        name, _, build = spec
        if name not in built:
            built[name] = build()
        return built[name]

    out: list[tuple[str, PermutationGroup]] = []
    for spec in atoms:
        if spec[1] == order:
            out.append((_spell(spec[0]), get(spec)))

    for k in (2, 3):
        for combo in itertools.combinations_with_replacement(atoms, k):
            if prod(o for _, o, _ in combo) != order:
                continue
            group = get(combo[0])
            for spec in combo[1:]:
                group = _product(group, get(spec))
            out.append((" x ".join(_spell(n) for n, _, _ in combo), group))

    for top_name, top in _WREATH_TOPS:
        b = top()
        if order % b.order:
            continue
        root = _exact_root(order // b.order, b.degree)
        if root is None:
            continue
        for spec in atoms:
            if spec[1] == root:
                out.append((f"{_spell(spec[0])} wr {top_name}", _wreath(get(spec), b)))

    return tuple(out)


#: Simple groups no product spells, keyed by
#: ``(order, abelian, |centre|, |derived subgroup|)``. A non-abelian group equal
#: to its own derived subgroup with trivial centre is perfect and centreless,
#: which pins this down at this order. PSL(3,2) is the Fano plane's automorphism
#: group (thesis Figure 5.2).
_SPECIAL: dict[tuple[int, bool, int, int], str] = {
    (168, False, 1, 168): "PSL(3,2)",
}

#: Where the catalogue's spelling differs from the thesis'. Applied per *factor*,
#: so ``D3`` reads as ``S3`` standalone and in ``S3 x D4`` alike -- naming the
#: same group two ways in one artifact is the defect this avoids.
_ALIASES: dict[str, str] = {"D3": "S3"}


def _spell(name: str) -> str:
    return _ALIASES.get(name, name)


def _named_cyclic(group: "PermutationGroup") -> Optional[str]:
    """``C{n}`` when ``group`` is cyclic: abelian with an element of full order."""
    if not group.is_abelian():
        return None
    n = group.order
    if any(perm_order(p) == n for p in group.elements):
        return f"C{n}"
    return None


def _named_dihedral(group: "PermutationGroup") -> Optional[str]:
    """``D{m}`` when ``group`` looks dihedral of order ``2m``.

    ``D_m`` is ``m`` rotations and ``m`` reflections: an element of order ``m``,
    and involutions numbering ``m``, or ``m + 1`` when ``m`` is even because the
    half-turn is one too. Same standing as everything else here -- an invariant
    match, not an isomorphism proof.
    """
    n = group.order
    if n % 2 or n < 6 or group.is_abelian():
        return None
    m = n // 2
    if not any(perm_order(p) == m for p in group.elements):
        return None
    involutions = sum(1 for p in group.elements if perm_order(p) == 2)
    return f"D{m}" if involutions == (m + 1 if m % 2 == 0 else m) else None


@dataclass(frozen=True, slots=True)
class GroupIdentification:
    """The result of naming a group."""

    name: str
    order: int
    abelian: bool
    method: str  # "trivial" | "catalogue" | "special" | "unidentified"

    def __str__(self) -> str:
        return self.name


def identify(group: PermutationGroup) -> GroupIdentification:
    """Name ``group`` by invariant fingerprint. See the module docstring.

    Returns an ``order N`` placeholder when nothing matches, rather than
    guessing -- an unnamed group is a prompt to run the SageMath backend, not a
    result to quote.
    """
    order = group.order
    if order == 1:
        return GroupIdentification("C1", 1, True, "trivial")

    abelian = group.is_abelian()

    for name in (_named_cyclic(group), _named_dihedral(group)):
        if name is not None:
            return GroupIdentification(_spell(name), order, abelian, "catalogue")

    if order <= MAX_CATALOGUE_ORDER:
        cheap = group.cheap_signature()
        matches = [
            (name, c) for name, c in _candidates(order) if c.cheap_signature() == cheap
        ]
        if matches:
            fp = group.fingerprint()
            for name, candidate in matches:
                if candidate.fingerprint() == fp:
                    return GroupIdentification(name, order, abelian, "catalogue")

        key = (order, abelian, len(group.centre()), len(group.derived_subgroup()))
        if key in _SPECIAL:
            return GroupIdentification(_SPECIAL[key], order, abelian, "special")

    return GroupIdentification(
        f"order {order} ({'abelian' if abelian else 'non-abelian'}, unidentified)",
        order,
        abelian,
        "unidentified",
    )
