"""Permutation groups, without SageMath.

The thesis names every node's automorphism group -- ``C2``, ``D4``, ``S4``,
``C2 x S4``, ``PSL(3,2)``, ``(((C2 x C2 x C2 x C2) : C2) : C2) : C2``
(Figures 5.1-5.4). The legacy notebooks got those from GAP via SageMath, which
is not on every machine this runs on. This is the pure-Python fallback; where
Sage is present :mod:`fka.backends.sage_backend` defers to GAP's
``StructureDescription``, which is authoritative.

Naming is by *invariant fingerprint*, not a proof of isomorphism. A group is
matched against a catalogue of cyclic, dihedral, symmetric, alternating and
quaternion groups and their direct products, on order, the multiset of element
orders, abelian-ness and centre order, derived subgroup order, and the multiset
of conjugacy class sizes. Two non-isomorphic groups agreeing on all five would
be misnamed -- it does not happen for anything in the thesis' figures, and the
catalogue is small enough to check, but the limitation is real. :func:`identify`
reports how it matched and returns an ``order N`` placeholder rather than a
guess when nothing fits.

Permutations are tuples of images on ``0 .. n-1``: ``p[i]`` is the image of ``i``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Optional, Sequence

__all__ = [
    "Perm",
    "identity",
    "compose",
    "inverse",
    "perm_order",
    "cycle_notation",
    "closure",
    "PermutationGroup",
    "identify",
]

Perm = tuple[int, ...]

#: Upper bound on how many group elements will be enumerated. Every group in
#: the thesis is far below this; the cap turns a runaway case into a clear
#: error instead of an apparent hang.
MAX_GROUP_ORDER = 200_000


def identity(n: int) -> Perm:
    return tuple(range(n))


def compose(p: Perm, q: Perm) -> Perm:
    """``(p . q)(i) = p(q(i))``."""
    return tuple(p[q[i]] for i in range(len(q)))


def inverse(p: Perm) -> Perm:
    out = [0] * len(p)
    for i, x in enumerate(p):
        out[x] = i
    return tuple(out)


def perm_order(p: Perm) -> int:
    """Multiplicative order of ``p``."""
    n = len(p)
    seen = [False] * n
    from math import lcm

    order = 1
    for i in range(n):
        if seen[i]:
            continue
        length = 0
        j = i
        while not seen[j]:
            seen[j] = True
            j = p[j]
            length += 1
        order = lcm(order, length)
    return order


def cycle_notation(p: Perm, *, one_indexed: bool = True) -> str:
    """Render ``p`` in disjoint-cycle notation, e.g. ``(1,4)(5,6)``.

    Fixed points are omitted; the identity renders as ``()``.
    """
    shift = 1 if one_indexed else 0
    n = len(p)
    seen = [False] * n
    parts: list[str] = []
    for i in range(n):
        if seen[i] or p[i] == i:
            seen[i] = True
            continue
        cycle = []
        j = i
        while not seen[j]:
            seen[j] = True
            cycle.append(j + shift)
            j = p[j]
        if len(cycle) > 1:
            parts.append("(" + ",".join(map(str, cycle)) + ")")
    return "".join(parts) if parts else "()"


def closure(generators: Sequence[Perm], n: int, *, cap: int = MAX_GROUP_ORDER) -> list[Perm]:
    """All elements of the group generated by ``generators`` (breadth-first)."""
    e = identity(n)
    seen = {e}
    frontier = [e]
    gens = [g for g in generators if g != e]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(g, x)
                if y not in seen:
                    seen.add(y)
                    if len(seen) > cap:
                        raise ValueError(
                            f"group exceeded {cap} elements; refusing to enumerate further"
                        )
                    nxt.append(y)
        frontier = nxt
    return sorted(seen)


@dataclass(slots=True)
class PermutationGroup:
    """A finite permutation group given by its full element list.

    Built from generators via :meth:`from_generators`. Holding every element is
    wasteful in general but is the simplest thing that supports the invariants
    below exactly, and the groups here are small by construction.
    """

    degree: int
    elements: list[Perm]
    generators: list[Perm] = field(default_factory=list)
    #: Memoised invariants. The full fingerprint costs O(|G|^2) compositions,
    #: and catalogue lookup compares many candidates against one query.
    _cheap: Optional[tuple] = None
    _fingerprint: Optional[tuple] = None

    @classmethod
    def from_generators(
        cls, generators: Sequence[Perm], n: int, *, cap: int = MAX_GROUP_ORDER
    ) -> "PermutationGroup":
        elements = closure(generators, n, cap=cap)
        return cls(degree=n, elements=elements, generators=list(generators))

    @property
    def order(self) -> int:
        return len(self.elements)

    def is_trivial(self) -> bool:
        return self.order == 1

    def element_order_profile(self) -> tuple[tuple[int, int], ...]:
        """Sorted ``(element order, count)`` pairs."""
        counts: dict[int, int] = {}
        for p in self.elements:
            o = perm_order(p)
            counts[o] = counts.get(o, 0) + 1
        return tuple(sorted(counts.items()))

    def is_abelian(self) -> bool:
        gens = self.generators or self.elements
        return all(compose(a, b) == compose(b, a) for a in gens for b in gens)

    def centre(self) -> list[Perm]:
        return [z for z in self.elements if all(
            compose(z, g) == compose(g, z) for g in self.elements
        )]

    def derived_subgroup(self) -> list[Perm]:
        """The commutator subgroup ``[G, G]``."""
        comms = set()
        for a in self.elements:
            ai = inverse(a)
            for b in self.elements:
                comms.add(compose(compose(a, b), compose(ai, inverse(b))))
        return closure(sorted(comms), self.degree)

    def conjugacy_class_sizes(self) -> tuple[int, ...]:
        remaining = set(self.elements)
        sizes: list[int] = []
        while remaining:
            x = next(iter(remaining))
            cls = {compose(compose(g, x), inverse(g)) for g in self.elements}
            sizes.append(len(cls))
            remaining -= cls
        return tuple(sorted(sizes))

    def orbits(self) -> list[tuple[int, ...]]:
        """Orbits of the group on ``0 .. degree-1``, ascending."""
        unseen = set(range(self.degree))
        out: list[tuple[int, ...]] = []
        while unseen:
            v = min(unseen)
            orb = sorted({p[v] for p in self.elements})
            out.append(tuple(orb))
            unseen -= set(orb)
        return out

    def minimal_generators(self) -> list[Perm]:
        """A small (greedy, not provably minimum) generating set.

        Elements are tried in descending order so high-order elements are
        picked first, which tends to give the short presentations the thesis
        quotes.
        """
        if self.order == 1:
            return []
        chosen: list[Perm] = []
        current = {identity(self.degree)}
        pool = sorted(self.elements, key=lambda p: -perm_order(p))
        for p in pool:
            if p in current:
                continue
            chosen.append(p)
            current = set(closure(chosen, self.degree))
            if len(current) == self.order:
                break
        return chosen

    def cheap_signature(self) -> tuple:
        """Invariants costing ``O(|G| * degree)``: order, element orders, abelian.

        Used to reject catalogue candidates before paying for the full
        fingerprint, which needs conjugacy classes and so costs ``O(|G|^2)``.
        """
        if self._cheap is None:
            self._cheap = (self.order, self.element_order_profile(), self.is_abelian())
        return self._cheap

    def fingerprint(self) -> tuple:
        """Invariants used to name the group. See the module docstring."""
        if self._fingerprint is None:
            self._fingerprint = self.cheap_signature() + (
                len(self.centre()),
                len(self.derived_subgroup()),
                self.conjugacy_class_sizes(),
            )
        return self._fingerprint


# ----------------------------------------------------------------------
# a catalogue of named small groups
# ----------------------------------------------------------------------
def _cyclic(n: int) -> PermutationGroup:
    gen = tuple((i + 1) % n for i in range(n))
    return PermutationGroup.from_generators([gen], n)


def _dihedral(n: int) -> PermutationGroup:
    """Symmetries of the ``n``-gon; order ``2n``."""
    rot = tuple((i + 1) % n for i in range(n))
    ref = tuple((-i) % n for i in range(n))
    return PermutationGroup.from_generators([rot, ref], n)


def _symmetric(n: int) -> PermutationGroup:
    gens = [tuple(range(1, n)) + (0,)]
    swap = list(range(n))
    swap[0], swap[1] = swap[1], swap[0]
    gens.append(tuple(swap))
    return PermutationGroup.from_generators(gens, n)


def _alternating(n: int) -> PermutationGroup:
    gens = []
    for i in range(n - 2):
        p = list(range(n))
        p[i], p[i + 1], p[i + 2] = p[i + 1], p[i + 2], p[i]
        gens.append(tuple(p))
    return PermutationGroup.from_generators(gens, n)


def _quaternion8() -> PermutationGroup:
    """Q8 as a regular permutation group on 8 points."""
    i = (1, 2, 3, 0, 7, 4, 5, 6)
    j = (4, 7, 6, 5, 2, 1, 0, 3)
    return PermutationGroup.from_generators([i, j], 8)


def _direct_product(a: PermutationGroup, b: PermutationGroup) -> PermutationGroup:
    """Direct product acting on the disjoint union of the two point sets."""
    na, nb = a.degree, b.degree
    n = na + nb
    gens = []
    for g in a.generators or a.elements:
        gens.append(tuple(g) + tuple(na + i for i in range(nb)))
    for g in b.generators or b.elements:
        gens.append(tuple(range(na)) + tuple(na + g[i] for i in range(nb)))
    return PermutationGroup.from_generators(gens, n)


def _wreath(a: PermutationGroup, b: PermutationGroup) -> PermutationGroup:
    """The wreath product ``A wr B``, acting imprimitively.

    ``B`` permutes ``m = b.degree`` blocks, each a copy of ``A``'s domain, and
    ``A`` acts inside each block. The order is ``|A|^m * |B|``.

    These matter here specifically: the thesis identifies the automorphism group
    at the root of the f2/g2 tree as ``D4 wr S2`` -- equivalently
    ``(((C2 x C2 x C2 x C2) : C2) : C2) : C2`` -- and Cameron's proposition
    (thesis Section 4.4) predicts that automorphism groups of cographs, hence of
    the corresponding clique hypergraphs, are built from direct and wreath
    products with symmetric groups. A catalogue of direct products alone could
    never name them.
    """
    p, m = a.degree, b.degree
    n = p * m
    gens: list[Perm] = []
    for g in a.generators or a.elements:
        img = list(range(n))
        for i in range(p):
            img[i] = g[i]
        gens.append(tuple(img))
    for h in b.generators or b.elements:
        img = [0] * n
        for blk in range(m):
            for i in range(p):
                img[blk * p + i] = h[blk] * p + i
        gens.append(tuple(img))
    return PermutationGroup.from_generators(gens, n)


#: ``(name, order, builder)`` for every atomic group, built on demand.
#:
#: Orders are stated in closed form so that :func:`_candidates` can select the
#: relevant groups arithmetically and construct only those. Building the whole
#: catalogue eagerly is not viable: the fingerprint needs conjugacy classes,
#: which cost ``O(|G|^2)`` compositions, and there are hundreds of products.
_AtomSpec = tuple[str, int, object]


@lru_cache(maxsize=1)
def _atom_specs() -> tuple[_AtomSpec, ...]:
    from math import factorial

    specs: list[_AtomSpec] = []
    # Include modest prime orders used in exploratory work.  The old upper
    # bound stopped at 100, so the elementary cyclic group C101 fell through as
    # "unidentified" even though constructing it is cheap.
    for n in range(2, 257):
        specs.append((f"C{n}", n, lambda n=n: _cyclic(n)))
    # The thesis (and SageMath's DihedralGroup) write the symmetry group of the
    # n-gon as Dn, so D4 has order 8.
    for n in range(3, 33):
        specs.append((f"D{n}", 2 * n, lambda n=n: _dihedral(n)))
    for n in range(3, 8):
        specs.append((f"S{n}", factorial(n), lambda n=n: _symmetric(n)))
    for n in range(4, 8):
        specs.append((f"A{n}", factorial(n) // 2, lambda n=n: _alternating(n)))
    specs.append(("Q8", 8, _quaternion8))
    return tuple(specs)


#: Groups above this order are not matched against the catalogue: enumerating
#: their elements and conjugacy classes stops being cheap, and nothing in the
#: thesis needs it. Larger groups fall through to :data:`_SPECIAL` or come back
#: unidentified, which is a prompt to run the SageMath backend.
MAX_CATALOGUE_ORDER = 2_000


@lru_cache(maxsize=256)
def _candidates(order: int) -> tuple[tuple[str, PermutationGroup], ...]:
    """Named groups of exactly ``order``, cheapest spelling first.

    Search order is: atoms, then two-factor direct products, then three-factor,
    then wreath products. Earlier entries win ties, so a group is named ``S4``
    rather than as some product that happens to be isomorphic to it.
    """
    specs = _atom_specs()
    built: dict[str, PermutationGroup] = {}

    def get(name: str, build) -> PermutationGroup:
        if name not in built:
            built[name] = build()
        return built[name]

    out: list[tuple[str, PermutationGroup]] = []

    for name, o, build in specs:
        if o == order:
            out.append((name, get(name, build)))

    divisors = [(n, o, b) for (n, o, b) in specs if o <= order and order % o == 0]

    for i, (n1, o1, b1) in enumerate(divisors):
        for n2, o2, b2 in divisors[i:]:
            if o1 * o2 == order:
                out.append(
                    (f"{n1} x {n2}", _direct_product(get(n1, b1), get(n2, b2)))
                )

    for i, (n1, o1, b1) in enumerate(divisors):
        for j in range(i, len(divisors)):
            n2, o2, b2 = divisors[j]
            if order % (o1 * o2):
                continue
            for n3, o3, b3 in divisors[j:]:
                if o1 * o2 * o3 == order:
                    out.append(
                        (
                            f"{n1} x {n2} x {n3}",
                            _direct_product(
                                _direct_product(get(n1, b1), get(n2, b2)),
                                get(n3, b3),
                            ),
                        )
                    )

    # Wreath products A wr B with a small top group.
    tops = [(n, o, b) for (n, o, b) in specs if n in ("C2", "C3", "C4", "S3", "S4")]
    tops.append(("S2", 2, lambda: _cyclic(2)))
    top_degree = {"C2": 2, "S2": 2, "C3": 3, "C4": 4, "S3": 3, "S4": 4}
    for nb, ob, bb in tops:
        m = top_degree[nb]
        for na, oa, ba in specs:
            if oa**m * ob == order:
                out.append((f"{na} wr {nb}", _wreath(get(na, ba), get(nb, bb))))

    return tuple(out)


#: Simple groups the catalogue cannot build as a product, keyed by
#: ``(order, abelian, |centre|, |derived subgroup|)``. A non-abelian group that
#: equals its own derived subgroup and has trivial centre is perfect and
#: centreless, which pins these down at these orders. PSL(3,2) is the
#: automorphism group of the Fano plane (thesis Figure 5.2).
_SPECIAL: dict[tuple[int, bool, int, int], str] = {
    (168, False, 1, 168): "PSL(3,2)",
    (60, False, 1, 60): "A5",
    (360, False, 1, 360): "A6",
}

#: Preferred spellings where the catalogue's first match differs from the
#: notation the thesis uses.
_ALIASES: dict[str, str] = {
    "D3": "S3",
    "C2 x S2": "C2 x C2",
}


@dataclass(frozen=True, slots=True)
class GroupIdentification:
    """The result of naming a group."""

    name: str
    order: int
    abelian: bool
    method: str  # "trivial" | "catalogue" | "special" | "unidentified"

    def __str__(self) -> str:
        return self.name


def identify(group: PermutationGroup) -> GroupIdentification:
    """Name ``group`` by invariant fingerprint. See the module docstring.

    Returns an ``order N`` placeholder when nothing matches, rather than
    guessing -- an unnamed group is a prompt to run the SageMath backend, not a
    result to quote.
    """
    order = group.order
    if order == 1:
        return GroupIdentification("C1", 1, True, "trivial")

    abelian = group.is_abelian()

    if order <= MAX_CATALOGUE_ORDER:
        cheap = group.cheap_signature()
        matches = [
            (name, c) for name, c in _candidates(order) if c.cheap_signature() == cheap
        ]
        if matches:
            fp = group.fingerprint()
            for name, candidate in matches:
                if candidate.fingerprint() == fp:
                    return GroupIdentification(
                        _ALIASES.get(name, name), order, abelian, "catalogue"
                    )

        key = (order, abelian, len(group.centre()), len(group.derived_subgroup()))
        if key in _SPECIAL:
            return GroupIdentification(_SPECIAL[key], order, abelian, "special")

    return GroupIdentification(
        f"order {order} ({'abelian' if abelian else 'non-abelian'}, unidentified)",
        order,
        abelian,
        "unidentified",
    )
