"""Self-dual functions, and primitivity as a read-once certificate.

``MBF = Tr(MBF)`` iff its term set is *intersecting* and *not 2-colourable*:
for every ``S``, exactly one of ``S``, ``V \\ S`` contains a term. That is one
``2^n`` scan, so self-duality never needs Berge's method. The Fano plane is the
thesis' example (Section 3.3, p.26); the only other one among the Witt designs
is ``S(4,5,11)``, built by :func:`fka.instances.witt_11` from the ternary Golay
code.

Read-once is decided in :mod:`fka.properties` by Gurvich's criterion. There is a
second certificate that applies where conformality is awkward:

    Aut(MBF) primitive and not S_n or A_n  ==>  MBF is not read-once.

A read-once function's primal graph is a cograph, so ``Aut(MBF)`` is the
cotree's group, an iterated direct/wreath product of symmetric groups
(thesis 4.4.15); the subtrees at any level are a block system unless the cotree
has depth 1, which gives ``S_n``. Fano's ``PGL(3,2)`` and ``S(4,5,11)``'s
``M_11`` both settle it in one line.

Automorphisms come from :func:`fka.automorphism.term_set_automorphisms`, the
one search in the project. Enumeration is exponential in general, so these take
a cap; a partial subgroup with no nontrivial block still *proves* primitivity,
since every block of a group is a block of each of its subgroups.
"""

from __future__ import annotations

import itertools
from typing import Optional, Sequence

from .automorphism import term_set_automorphisms
from .groups import MAX_GROUP_ORDER
from .hypergraph import Hypergraph, bits, verts

__all__ = [
    "is_self_dual",
    "is_intersecting",
    "subset_orbits",
    "automorphisms",
    "pair_automorphisms",
    "is_transitive",
    "is_primitive",
    "fano",
    "FANO_LINES",
]


def is_self_dual(MBF: Hypergraph) -> bool:
    """``MBF == Tr(MBF)``, by the ``2^n`` scan rather than by building ``Tr``."""
    full = (1 << MBF.n) - 1
    for S in range(1 << MBF.n):
        a = any((t & S) == t for t in MBF.edges)
        b = any((t & (full ^ S)) == t for t in MBF.edges)
        if a == b:
            return False
    return True


def is_intersecting(MBF: Hypergraph) -> bool:
    """No two terms are disjoint."""
    return all(a & b for a, b in itertools.combinations(MBF.edges, 2))


def subset_orbits(gens: Sequence[Sequence[int]], n: int, k: int) -> list[tuple[int, ...]]:
    """Orbits of the ``k``-subsets of ``[n]`` under the group generated by ``gens``.

    Building a candidate as a union of orbits puts the group inside ``Aut`` by
    construction, which is what makes regularity automatic.
    """
    seen: set[int] = set()
    out = []
    for c in itertools.combinations(range(n), k):
        e = bits(c)
        if e in seen:
            continue
        orb, frontier = {e}, [e]
        while frontier:
            x = frontier.pop()
            for g in gens:
                y = bits(g[v] for v in verts(x))
                if y not in orb:
                    orb.add(y)
                    frontier.append(y)
        seen |= orb
        out.append(tuple(sorted(orb)))
    return out


def automorphisms(MBF: Hypergraph, cap: Optional[int] = None):
    """Every automorphism of ``MBF`` as a permutation of ``0..MBF.n-1``.

    Returns ``(perms, capped)``; ``capped`` says the enumeration stopped early,
    so ``len(perms)`` is a lower bound on the order rather than the order.
    """
    return term_set_automorphisms(
        [MBF], cap=MAX_GROUP_ORDER if cap is None else cap, partial=True
    )


def pair_automorphisms(cnf: Hypergraph, dnf: Hypergraph, cap: Optional[int] = None):
    """Permutations preserving both sides' term sets separately.

    The right object mid-recursion, where the subproblems need not be a dual
    pair and ``Aut(C) = Aut(D)`` (Lemma 3.3.1) no longer applies.
    """
    return term_set_automorphisms(
        [cnf, dnf], cap=MAX_GROUP_ORDER if cap is None else cap, partial=True
    )


def is_transitive(perms: Sequence[Sequence[int]], n: int) -> bool:
    return bool(perms) and len({p[0] for p in perms}) == n


def is_primitive(perms: Sequence[Sequence[int]], n: int) -> bool:
    """No nontrivial block system. Assumes ``perms`` is transitive on ``[n]``.

    Sound on a subgroup in one direction only: ``True`` proves the full group is
    primitive, ``False`` does not prove it is imprimitive.
    """
    for b in range(1, n):
        block = {0, b}
        changed = True
        while changed:
            changed = False
            for g in perms:
                img = {g[x] for x in block}
                if img & block and not img <= block:
                    block |= img
                    changed = True
        if len(block) != n:
            return False
    return True


#: The seven lines of PG(2,2), 1-indexed (thesis Definition 5.2.1, p.50).
#: Self-transversal, ``|Aut| = 168``, 2-transitive. The one definition;
#: :mod:`fka.instances` builds its Fano families from these.
FANO_LINES: tuple[tuple[int, ...], ...] = (
    (1, 2, 4), (2, 3, 5), (3, 4, 6), (4, 5, 7),
    (1, 5, 6), (2, 6, 7), (1, 3, 7),
)


def fano() -> Hypergraph:
    """``S(2,3,7)``, the Fano plane."""
    return Hypergraph.from_sets(7, [list(e) for e in FANO_LINES], one_indexed=True)
